In [1]:
n=10

In [2]:
import numpy as np
import random as rd

In [3]:
def grille(n):
    a=np.zeros((n,n),dtype=int)
    k=1
    r=1
    for i in range(n):
        if i==k:
            for j in range(n):
                if j==r:
                    a[i,j]=1
    return a

In [4]:
grille(10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
M=grille(n)

In [6]:


def etat_incubation1(M, p1, p2, x, y, pas, dictio):
    resultat = M
    
    
    L=[(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    voisin_infecte=0
    
    
                
    if M[x,y] ==2 :
        resultat[x,y]=2 #personnes rétablies
    
    elif M[x,y] ==3:
        resultat[x,y] =3  #personnes dcdées
        
    
    
    elif M[x,y]==0:  #personnes saines
        
        for (dx, dy) in L:
            
            if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y+dy>=0):
                if M[x+dx,y+dy]==1 :
                    if np.random.random() <= p2:
                       
                        voisin_infecte=voisin_infecte+1
    if voisin_infecte>0:
        resultat[x,y]=1
        
    if(resultat[x,y]==1):
    # Incrémente le compteur de tous les maladesdictio=dict()
        if (x,y) in dictio :
            dictio[(x,y)]=dictio[(x,y)]+1   # On entre en incubation 
    
    # Nouvel infecté : on le rajoute au dictionnaire
        else:
            dictio[(x,y)]=1
        
   
    

    
    # En incubation depuis "pas" tours : on devient soit rétabli soit décédé selon une propabilité  p1
    if (x,y) in dictio and dictio[(x,y)] >= pas:
        if np.random.random() <= p1:
            resultat[x,y]=3
        else:
            resultat[x,y]=2
        
        dictio.pop((x,y))
            
    
    return resultat,dictio

In [7]:
etat_incubation1(M,0.5,0.4,0,1,4,{})

(array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), {(0, 1): 1})

In [8]:
p1=0.5
n=5
p2=1
M=grille(n)

pas=2
d={}

In [54]:
def next_step_incubation(M,d, verbose=False):
    
    for i in range(n):
        for j in range(n):
            M, d = etat_incubation1(M,p1,p2,i,j,pas,d)
            if verbose:
                print(M)
                print(d)
    
    return M

In [55]:
next_step_incubation(M,d)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
p1=0.4
n=5
p2=0.5
M=grille(n)
pas=4

In [12]:
def simulation(max_itere=10):
    cpt=0
    resultat=[]    
    new_state=next_step_incubation(M,d)
    while(cpt<max_itere):
        resultat.append((new_state).copy())
        new_state= next_step_incubation(new_state,d)
        cpt = cpt+1
        
    return resultat

In [13]:
simulation()
          
          

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
{(0, 0): 1, (0, 1): 1, (0, 2): 1, (0, 3): 1, (0, 4): 1, (1, 0): 1, (1, 1): 1, (1, 2): 1, (1, 3): 1, (1, 4): 1, (2, 0): 1, (2, 1): 1, (2, 2): 1, (2, 3): 1, (2, 4): 1, (3, 0): 1, (3, 1): 1, (3, 2): 1, (3, 3): 1, (3, 4): 1, (4, 0): 1, (4, 1): 1, (4, 2): 1, (4, 3): 1, (4, 4): 1}
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
{(0, 0): 1, (0, 1): 2, (0, 2): 1, (0, 3): 1, (0, 4): 1, (1, 0): 1, (1, 1): 1, (1, 2): 1, (1, 3): 1, (1, 4): 1, (2, 0): 1, (2, 1): 1, (2, 2): 1, (2, 3): 1, (2, 4): 1, (3, 0): 1, (3, 1): 1, (3, 2): 1, (3, 3): 1, (3, 4): 1, (4, 0): 1, (4, 1): 1, (4, 2): 1, (4, 3): 1, (4, 4): 1}
[[0 1 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
{(0, 0): 1, (0, 1): 2, (0, 2): 2, (0, 3): 1, (0, 4): 1, (1, 0): 1, (1, 1): 1, (1, 2): 1, (1, 3): 1, (1, 4): 1, (2, 0): 1, (2, 1): 1, (2, 2): 1, (2, 3): 1, (2, 4): 1, (3, 0): 1, (3, 1): 1, (3, 2): 1, (3, 3): 1, (3, 4): 1, (4, 0): 1, (4, 1): 1, (4, 2):

[array([[0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 2, 3]]), array([[2, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 2, 3]]), array([[2, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 2, 3]]), array([[2, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 2, 3]]), array([[2, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 2, 3]]), array([[2, 3, 2, 3, 3],
        [2, 3, 3, 3, 3],
        [3, 3, 2, 2, 2],
        [3, 2, 3, 3, 2],
        [3, 2, 2, 

deplacement des individus

In [14]:
import numpy as np


In [15]:
n=3
M=grille(n)


In [16]:
def grille_case_vide(n,M):
    N=grille(n)
    for i in range(n):
        if( i%2==0 ):
            for j in range(n):
                if(j%2==0):
                    N[i,j]=5 #case vide
    return N
                    

In [17]:
grille_case_vide(n,M)

array([[5, 0, 5],
       [0, 1, 0],
       [5, 0, 5]])

In [18]:
M

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [19]:
import random

In [20]:
N=grille_case_vide(n,M)

In [21]:
N

array([[5, 0, 5],
       [0, 1, 0],
       [5, 0, 5]])

In [22]:
def deplacement(N,x,y,p):
    d=[]
    vide=5 #case vide
    
    if(N[x,y]!= vide):
         if np.random.random() <= p: 
            for i in range(n):
        
                for j in range(n):
                    if (N[(i,j)]==vide):
                        if not (i,j) in d:
                            d.append((i,j))
            (k,l)=random.choice(d)
    
            N[k,l]=N[x,y]
            N[x,y]=5 # la case devient vide apres le deplacement de la personne (x,y)
            return (k,l)
    
    return (x,y)
        

In [23]:
deplacement(N,1,1,0.5)

(2, 0)

In [26]:
x = 1
y = 2
p = 0.5

deplacement(N,x,y,p)
M=grille(n)
N=grille_case_vide(n,M)

import numpy as np
import random

In [29]:
M=grille(n)
N=grille_case_vide(n,M)
p=0.5

import numpy as np
import random

In [64]:
def etat_incubation_deplac(N, p1, p2, x, y, pas, dictio):
    
    resultat = N  # grille de départ
    
    L = [(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    voisin_infecte = 0 
    
    if N[x, y] == 2:  # i.e. personne rétablie
        resultat[x, y] = 2  # reste rétablie
    elif N[x, y] == 3:  # i.e personne décédée
        resultat[x, y] = 3  # reste décédée
    elif N[x, y] == 5: # i.e. cases vides
        resultat[x, y] = 5
    elif N[x,y]==0:  # i.e. personnes saines
        for (dx, dy) in L:  # pour chaque voisin
            if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y+dy>=0):  # bornes grille
                if N[x+dx,y+dy]==1:  # i.e. infecté
                    voisin_infecte += 1
    
    # Gestion de l'infection.
    if voisin_infecte > 0:
        if np.random.random() <= p2:
            resultat[x, y] = 1  # est infecté
    
    # Définition / mise à jour du temps d'incubation.
    if(resultat[x, y] == 1):
        if (x, y) in dictio :
            # Incrémente le compteur de tous les maladesdictio=dict()
            dictio[(x, y)] = dictio[(x, y)] + 1   # on entre en incubation 
        else:
            # Nouvel infecté : on le rajoute au dictionnaire
            dictio[(x, y)] = 1
    
    # En incubation depuis "pas" tours : on devient soit rétabli soit décédé selon une propabilité p1.
    if (x, y) in dictio and dictio[(x, y)] >= pas:
        if np.random.random() <= p1:
            resultat[x, y] = 3  # i.e. meurt
        else:
            resultat[x, y] = 2  # i.e. se rétabli
        dictio.pop((x, y))
    
    # Gestion des déplacements.
    if (x, y) in dictio:   
        (x_, y_) = deplacement(N, x, y, p)
        if (x_, y_) != (x, y):
            dictio[(x_, y_)] = dictio[(x, y)]
            dictio.pop((x, y))
    
    return resultat, dictio

In [65]:
 etat_incubation_deplac(N, 0.5, 0.4, 1, 1, 4, {})

(array([[1, 0, 5],
        [0, 5, 0],
        [5, 0, 5]]), {(0, 0): 1})

In [85]:
p1=0.5
n=3
p2=1
pas=1
d={}
M=grille(n)
N=grille_case_vide(n,M)
p=0.5
import numpy as np
import random

In [86]:
def next_step_incubation_deplac(N,d,verbose=False):
    
    
    
    for i in range(n):
        
        for j in range(n):
            
            N,d =etat_incubation_deplac(N,p1,p2,i,j,pas,d)
            if verbose:
                print(N)
                print(d)
    
    return N

In [87]:
next_step_incubation_deplac(N,{})

array([[5, 2, 5],
       [3, 2, 0],
       [5, 0, 5]])

In [88]:
p1=0.5
p2=1
M=grille(n)
p=0.5

import numpy as np
import random

pas=4

In [89]:
N=grille_case_vide(n,M)
print("n:\n {}".format(n))
print("M:\n {}".format(M))
print("N:\n {}".format(N))

n:
 3
M:
 [[0 0 0]
 [0 1 0]
 [0 0 0]]
N:
 [[5 0 5]
 [0 1 0]
 [5 0 5]]


In [90]:
def simulation(max_itere=10, verbose=False):
    cpt=0
    N=grille_case_vide(n,M)
    if verbose:
        print("n:\n {}".format(n))
        print("M:\n {}".format(M))
        print("N:\n {}".format(N))    
    D=dict()
    result=[]
    result.append((N).copy())
    new_state=next_step_incubation_deplac(N,D)
    while(cpt<max_itere):
        result.append((new_state).copy())
        new_state= next_step_incubation_deplac(new_state,D, verbose=verbose)
        cpt = cpt+1
        
    return result,D

In [94]:
result,h=simulation(10, verbose=False)
for x in result:
    print(x)

[[5 0 5]
 [0 1 0]
 [5 0 5]]
[[5 1 1]
 [1 5 5]
 [1 1 5]]
[[5 1 1]
 [5 1 5]
 [1 1 5]]
[[5 1 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]
[[5 3 5]
 [2 3 5]
 [2 5 3]]


In [ ]:
%matplotlib notebook
from pylab import *
import numpy as np


x=0
y=0


def simulation(max_itere=100):
    M=grille(100)
    cpt=0
    resultat=[M.copy()]
    new_state=next_step_incubation(M,d)
    
    while (cpt < max_itere):
        resultat.append(new_state.copy())
        new_state= next_step_incubation(new_state,d)
        cpt = cpt+1
    
    return resultat

resultat_final = simulation(max_itere=49)

print(resultat_final)


import matplotlib.pyplot as plt
size = np.array(M.shape)
dpi = 10.0 
figsize= size[1]/float(dpi),size[0]/float(dpi)
#fig = plt.figure(figsize = figsize, dpi = dpi, facecolor = "white")
fig = plt.figure(facecolor = "white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon = False)
im=plt.imshow(M, interpolation = 'nearest', cmap ="viridis", vmin=0, vmax=3)
plt.xticks([]), plt.yticks([])
plt.colorbar()


import matplotlib.animation as animation

def update(i):
    #simulation_4param(max_itere=10)
    M = resultat_final[i]
    im.set_array(M)
    return im,

ani = animation.FuncAnimation(fig, update, frames=len(resultat_final), interval=500)
plt.show()