In [1]:
import numpy as np
import random as rd

In [2]:
n=5

In [3]:
def grille(n):
    a=np.zeros((n,n),dtype=int)
    k=1
    r=1
    for i in range(n):
        if i==k:
            for j in range(n):
                if j==r:
                    a[i,j]=1
    return a

In [4]:
grille(5)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
M=grille(n)

In [6]:
def etat_2param(x,y,M):
    
    print(M)
    L=[(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    
    print(x,y) 
    for (dx,dy) in L:
        if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y>=0):
            if M[x,y]==0:
                if M[x+dx,y+dy]==1:
                    M[x,y]=1
                    
                else:
                    M[x,y]=0
                    
    return M[x,y]
                            

In [7]:
etat_2param(2,0,M)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2 0


1

In [8]:
def next_step(M): 
    
    for i in range(n):
        j=0
        for j in range(n):
            M[i,j]=etat_2param(i,j,M)
            print(M[i,j])
    return M
            

In [9]:
next_step(M)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0 0
1
[[1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0 1
1
[[1 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0 2
1
[[1 1 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0 3
1
[[1 1 1 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0 4
1
[[1 1 1 1 1]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 0
1
[[1 1 1 1 1]
 [1 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 1
1
[[1 1 1 1 1]
 [1 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 2
1
[[1 1 1 1 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 3
1
[[1 1 1 1 1]
 [1 1 1 1 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 4
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2 0
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2 1
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
def simulation(max_itere=10):
    cpt=0
    resultat=[]
    new_state= next_step(M)
    
    while (cpt < max_itere):
        resultat.append(new_state.copy())
        
        new_state= next_step(new_state)
        cpt = cpt+1
        
    return resultat
    
        
        
    
    

In [11]:
simulation()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0 0
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0 1
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0 3
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0 4
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 0
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 1
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 3
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 4
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2 0
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2 1
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]

[array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 

# 4paramètres


In [12]:
import numpy

In [13]:
p1=0.5

M=grille(n)

In [14]:
def etat_4param(M,p1, x, y):
    resultat= grille(n)
    print(M)
    
    L=[(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    voisin_infecte=0
    
    if M[x,y] == 1:
                if numpy.random.random() <= p1:
                    resultat[x,y]=3
                else:
                    resultat[x,y]=2
    elif M[x,y] ==2 :
        resultat[x,y]=2
    
    elif M[x,y] ==3:
        resultat[x,y] =3
    
    else:
        
        for (dx, dy) in L:
            if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y+dy>=0):
                if M[x+dx,y+dy]==1:
                    voisin_infecte= voisin_infecte+1
                else:
                    resultat[x,y]=0
            
                
            
        if (voisin_infecte >0):
            resultat[x,y] =1
    
    return resultat[x,y]
                    
                
                
      
                        
                    
    
    

In [15]:
etat_4param(M,p1,1,0)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


1

In [16]:
M=grille(n)

In [17]:
def next_step_4param(M):
  
    resultat=grille(n)
    for i in range(n):
        j=0
        for j in range(n):
            
            resultat[i,j]=etat_4param(M,p1,i,j)
            print(resultat[i,j])
    return resultat
    

In [18]:
next_step_4param(M)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0

array([[1, 1, 1, 0, 0],
       [1, 2, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
def simulation_4param(max_itere=10):
    cpt=0
    resultat=[]
    new_state=next_step_4param(M)
    while (cpt < max_itere):
        resultat.append(new_state.copy())
        
        new_state= next_step_4param(new_state)
        cpt = cpt+1
        
    return resultat
    

In [20]:
simulation_4param(19)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
3
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0

[array([[1, 1, 1, 0, 0],
        [1, 3, 1, 0, 0],
        [1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]), array([[3, 3, 3, 1, 0],
        [2, 3, 3, 1, 0],
        [2, 2, 2, 1, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 0]]), array([[3, 3, 3, 3, 1],
        [2, 3, 3, 2, 1],
        [2, 2, 2, 2, 1],
        [2, 2, 3, 2, 1],
        [1, 1, 1, 1, 1]]), array([[3, 3, 3, 3, 3],
        [2, 3, 3, 2, 2],
        [2, 2, 2, 2, 3],
        [2, 2, 3, 2, 3],
        [3, 3, 2, 3, 3]]), array([[3, 3, 3, 3, 3],
        [2, 3, 3, 2, 2],
        [2, 2, 2, 2, 3],
        [2, 2, 3, 2, 3],
        [3, 3, 2, 3, 3]]), array([[3, 3, 3, 3, 3],
        [2, 3, 3, 2, 2],
        [2, 2, 2, 2, 3],
        [2, 2, 3, 2, 3],
        [3, 3, 2, 3, 3]]), array([[3, 3, 3, 3, 3],
        [2, 3, 3, 2, 2],
        [2, 2, 2, 2, 3],
        [2, 2, 3, 2, 3],
        [3, 3, 2, 3, 3]]), array([[3, 3, 3, 3, 3],
        [2, 3, 3, 2, 2],
        [2, 2, 2, 2, 3],
        [2, 2, 3, 2, 3],
        [3, 3, 2, 

In [21]:
result = _

In [22]:
for x in result:
    print(x)
    print()

[[1 1 1 0 0]
 [1 3 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[3 3 3 1 0]
 [2 3 3 1 0]
 [2 2 2 1 0]
 [1 1 1 1 0]
 [0 0 0 0 0]]

[[3 3 3 3 1]
 [2 3 3 2 1]
 [2 2 2 2 1]
 [2 2 3 2 1]
 [1 1 1 1 1]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 3]]

[[3 3 3 3 3]
 [2 3 3 2 2]
 [2 2 2 2 3]
 [2 2 3 2 3]
 [3 3 2 3 

In [23]:
def etat_incubation( M, p1, p2, x, y, pas,max_itere):
    resultat = grille(n)
    print(M)
    
    L=[(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    voisin_infecte=0
    
    if M[x,y] == 1:
        if numpy.random.random() <= p1:
            resultat[x,y]=3
        else:
            resultat[x,y]=2
    elif M[x,y] ==2 :
        resultat[x,y]=2
    
    elif M[x,y] ==3:
        resultat[x,y] =3
        
    
    else:
        
        for (dx, dy) in L:
            if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y+dy>=0):
                if M[x+dx,y+dy]==1:
                    if numpy.random.random() <= p2:
                        voisin_infecte= voisin_infecte+1
                    else:
                        resultat[x,y]=4
            
                
            
        if (voisin_infecte >0):
            resultat[x,y] =1
    
    return resultat[x,y]
                    

In [24]:
etat_incubation(M,0.5,0.4,4,4)

TypeError: etat_incubation() missing 2 required positional arguments: 'pas' and 'max_itere'

In [ ]:
p1=0.5
p2=0.4
M=grille(n)

In [ ]:
def next_step_incubation(M):
    resultat=grille(n)
    for i in range(n):
        j=0
        for j in range(n):
            
            resultat[i,j]=etat_incubation(M,p1,p2,i,j)
            print(resultat[i,j])
    return resultat
    

In [ ]:
next_step_incubation(M)

In [ ]:
def simulation_incubation(pas,max_itere=10):
    cpt=pas
    resultat=[]
    new_state=next_step_incubation(M)
    while(cpt<max_itere):
        resultat.append(new_state.copy())
        
        new_state= next_step_incubation(new_state)
        cpt = cpt+pas
        
    return resultat

In [ ]:
simulation_incubation(2)

In [ ]:
result = _

In [ ]:
for x in result:
    print(x)
    print()

In [ ]:
def etat_incubation2( M, p1, p2, x, y, pas,max_itere):
    t=0
    resultat = grille(n)
    print(M)
    
    L=[(1,0),(-1,0),(0,1),(0,-1),(1,-1),(1,1),(-1,1),(-1,-1)]
    voisin_infecte=0
    
    # TODO: un dictionnaire avec la position des infectés en train "d'incuber" en clef,
    # et le temps auquel ils ont été infecté (alternativement, le temps écoulé depuis leur infection)
    # À chaque étape de simulation, on parcourt le dictionnaire et les gens infectés depuis assez
    # longtemps changent d'état.
    # TODO : renommer pas en "temps_incub"
    
    if M[x,y] == 1:
        if numpy.random.random() <= p1:
            resultat[x,y]=3
        else:
            resultat[x,y]=2
    elif M[x,y] ==2 :
        resultat[x,y]=2
    
    elif M[x,y] ==3:
        resultat[x,y] =3
        
    
    else:
        
        for (dx, dy) in L:
            if (x+dx)<n and (x+dx)>=0 and (y+dy)<n and (y+dy>=0):
                if M[x+dx,y+dy]==1:
                    
                    if numpy.random.random() <= p2:
                        while (t<pas):
                            resultat[x,y]=4
                            for (dw, dz) in L:
                                if (x+dw)<n and (x+dw)>=0 and (y+dz)<n and (y+dz>=0):
                                    if M[x+dw,y+dz]==0:
                                        
                                
                       
                            
                            
                    else:
                        resultat[x,y]=5
            
                
            
        if (voisin_infecte >0):
            resultat[x,y] =1
    
    return resultat[x,y]